---
title: "data_simulation_long"
author: "Haotian Zheng"
date: "2024-08-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(remote)
library(MASS)
library(Matrix)
```



set working directory to working folder
```{r}
current_file_path = rstudioapi::getActiveDocumentContext()$path
current_dir = dirname(current_file_path)
setwd(current_dir)
```



number of year and observations
```{r}
observation_num = 1000
all_years = seq(1990, 2020, by = 2)
```



create dataframe
```{r}
data_raw = data.frame()
for (i in 1: observation_num) {
  num_years = sample(1:length(all_years), 1)
  year = sample(all_years, num_years)
  
  data_tmp = data.frame(
    id = i,
    year = year
  )
  
  data_raw = rbind(data_raw, data_tmp)
}

data_raw = data_raw %>% arrange(id, year)
n = nrow(data_raw)
```



create coefficients
$y_{ij} = \beta_0 +\beta_1 * x_{1ij} +\beta_2 * x_{2ij} + \beta_3 * x_{3ij} + b_{0i} +b_{1i} * x_{1ij} +b_{2i} * x_{2ij} + b_{3i} * x_{3ij} + \beta_4 * z_{1i} + \beta_5 * z_{2i} + \beta_6 * z_{3i} + \epsilon_{ij}$
```{r}
# beta_1 to beta_6
beta_0 = 4
beta_1 = 0.7
beta_2 = 2
beta_3 = 11
beta_4 = 3
beta_5 = 1.5
beta_6 = 12

n_random_effects = 4
mean_vector = rep(0, n_random_effects)
initial_matrix = matrix(runif(n_random_effects ^ 2, -1, 1), nrow = n_random_effects)
sym_matrix = (initial_matrix + t(initial_matrix)) / 2
random_effects_cov = nearPD(sym_matrix)$mat
rand_effect_matrix = mvrnorm(observation_num, mu = mean_vector, Sigma = random_effects_cov)

b_0i = rand_effect_matrix[, 1]
b_1i = rand_effect_matrix[, 2]
b_2i = rand_effect_matrix[, 3]
b_3i = rand_effect_matrix[, 4]
```



create covariates
```{r}
# time-varying covariates
data_raw$x1 = rnorm(n, mean = 4, sd = 5) + data_raw$year - 2003
data_raw$x2 = mapply(function(year) {
  rpois(1, round((year - 1980) / 5))
}, data_raw$year)
data_raw$x3 = mapply(function(year) {
  runif(1, min = (year - 2008) / 16, max = (year - 1998) / 16)
}, data_raw$year)

# individual covariates
z1 = exp(rnorm(observation_num, mean = log(sqrt(3.2)), sd = log(sqrt(5/4))))
z2 = rpois(observation_num, 2)
z3 = rgamma(observation_num, 3, 2)
data_raw$z1 = z1[data_raw$id]
data_raw$z2 = z2[data_raw$id]
data_raw$z3 = z3[data_raw$id]

# indicator
data_raw$indicator = sample(1:3, size = n, replace = TRUE, prob = c(0.6, 0.3, 0.1))
```



create outcomes
```{r}
# outcome
data_raw$y = beta_0 + beta_1 * data_raw$x1 + beta_2 * data_raw$x2 + beta_3 * data_raw$x3 +  b_0i[data_raw$id] + b_1i[data_raw$id] * data_raw$x1 + b_2i[data_raw$id] * data_raw$x2 + b_3i[data_raw$id] * data_raw$x3 + beta_4 * data_raw$z1 + beta_5 * data_raw$z2 + beta_6 * data_raw$z3

# sum
data_raw$x_sum = data_raw$x1 + data_raw$x2 + data_raw$x3
```



missing values
```{r}
introduce_missingness = function(data, mechanism, X, prob) {
  if (mechanism == "MCAR") {
    data[sample(1:nrow(data), size = round(nrow(data) * (1 - prob))), X] = NA
  } else if (mechanism == "MAR") {
    
    # in MAR, observation is based on complete cases
    objective_function = function(a, data, prob) {
      prob_try = plogis(a - 1 / sd(data$y) * data$y)
      mean_prob = mean(prob_try, na.rm = TRUE)
      return(abs(mean_prob - prob))  # to make the mean prob close to the target prob
    }
    # find the a
    optimized_a = optimize(objective_function, interval = c(-5, 5), data = data, prob = prob)$minimum
    # calculate new prob with new a
    prob = plogis(optimized_a - 1 / sd(data$y) * data$y)
    
    data[runif(nrow(data)) > prob, X] = NA
  }
  return(data)
}

data = introduce_missingness(data_raw, "MAR", "x1", 0.3)
data = introduce_missingness(data, "MAR", "x2", 0.7)
data = introduce_missingness(data, "MAR", "x3", 0.995)
data = introduce_missingness(data, "MAR", "z1", 0.9)
data = introduce_missingness(data, "MAR", "indicator", 0.4)
data$x_sum = data$x1 + data$x2 + data$x3
```



save the data set
```{r}
data_dir = paste0(current_dir, "/Data/")

if (!dir.exists(data_dir)) {
  dir.create(data_dir)
}

write.csv(data_raw, file.path(data_dir, "data_longitudinal_raw.csv"), row.names = F)
write.csv(data, file.path(data_dir, "data_longitudinal.csv"), row.names = F)
```



