---
title: "Final_imp"
author: "Haotian Zheng"
date: "2024-11-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




Longitudinal SumScore
```{r}
# imputation
data_use = data
data_use$id = as.integer(data_use$id)
data_use = data_use %>%
  mutate_all(~ifelse(. == "NaN", NA, .))

# set imputation parameters
ini = mice(data_use, maxit = 0)

pred = ini$pred
pred[, "id"] = -2
pred[c("x1", "x2", "x3"), "year"] = 2
pred[c("x1", "x2", "x3"), c("z1", "z2", "z3")] = 0
pred[c("z1", "z2", "z3"), c("x1", "x2", "x3")] = 0
pred[c("x1", "x2", "x3"), "x_sum"] = 0
pred["y", c("x1", "x2", "x3")] = 0
pred["x_sum", ] = 0
diag(pred) = 0

meth = ini$meth
meth[1: length(meth)] <- ""
meth[c("x1", "x2", "x3", "z1")] = c("2l.pmm", "2l.pmm", "2l.pmm", "pmm")
meth["x_sum"] = "~I(x1 + x2 + x3)"

post = make.post(data)
post["x1"] = "imp[[j]][, i] = squeeze(imp[[j]][, i], c(-13, 38))"
post["x2"] = "imp[[j]][, i] = squeeze(imp[[j]][, i], c(0, 5))"
post["x3"] = "imp[[j]][, i] = squeeze(imp[[j]][, i], c(-0.5, 1.5))"
post["z1"] = "imp[[j]][, i] = squeeze(imp[[j]][, i], c(1, 3.5))"
post["x_sum"] = "imp[[j]][, i] = squeeze(imp[[j]][, i], c(-13, 42))"

imp.use = mice(data, pred = pred, meth = meth, m = 5, maxit = 5, seed = 1018, printFlag = F)
```



diagnosis
```{r}
plot(imp.use)
densityplot(imp.use)
```



