---
title: "Longitudinal_imp_sim"
author: "Haotian Zheng"
date: "2024-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mice)
library(dplyr)
# library(ggplot2)
# library(micemd)
library(miceadds)
# library(remote)
# library(pan)
# library(miceRanger)
library(SimEngine)
library(MASS)
library(Matrix)
```



missing values
```{r}
introduce_missingness = function(data, mechanism, X, prob) {
  if (mechanism == "MCAR") {
    data[sample(1:nrow(data), size = round(nrow(data) * (1 - prob))), X] = NA
  } else if (mechanism == "MAR") {
    
    # in MAR, observation is based on complete cases
    objective_function = function(a, data, prob) {
      prob_try = plogis(a - 1 / sd(data$y) * data$y)
      mean_prob = mean(prob_try, na.rm = TRUE)
      return(abs(mean_prob - prob))  # to make the mean prob close to the target prob
    }
    # find the a
    optimized_a = optimize(objective_function, interval = c(-5, 5), data = data, prob = prob)$minimum
    # calculate new prob with new a
    prob = plogis(optimized_a - 1 / sd(data$y) * data$y)
    
    data[runif(nrow(data)) > prob, X] = NA
  }
  return(data)
}
```



create data
```{r}
create_data = function(observation_num, start_year, time_type, time_params, beta_1, id_type, id_params, beta_2) {
  all_years = seq(start_year, 2014, by = 2)
  data_raw = data.frame()
  for (i in 1: observation_num) {
    num_years = sample((1: length(all_years)), 1)
    year = sample(all_years, num_years)
    
    data_tmp = data.frame(
      id = i,
      year = year
    )
    
    data_raw = rbind(data_raw, data_tmp)
  }
  
  data_raw = data_raw %>% arrange(id, year) # raw dataframe, only id and year
  n = nrow(data_raw)
  
  n_random_effects = 2
  mean_vector = rep(0, n_random_effects)
  wishart_matrix = rWishart(1, df = n_random_effects + 2, Sigma = diag(n_random_effects))[,,1]
  random_effects_cov = wishart_matrix
  rand_effect_matrix = mvrnorm(observation_num, mu = mean_vector, Sigma = random_effects_cov)
  
  # random effect
  b_0i = rand_effect_matrix[, 1]
  b_1i = rand_effect_matrix[, 2]
  
  # time-varying covariates
  beta_0 = 4
  if (time_type == "Normal") {
    data_raw$x1 = rnorm(n, mean = time_params[1], sd = time_params[2]) + data_raw$year - 2003 +exp(rnorm(observation_num, mean = time_params[3], sd = time_params[4]))[data_raw$id]
  } else if (time_type == "Poisson") {
    data_raw$x1 = mapply(function(year) {
      rpois(1, round((year - 1980) / 5))
    }, data_raw$year) + rpois(observation_num, time_params[1])[data_raw$id]
  } else if (time_type == "Uniform") {
    data_raw$x1 = mapply(function(year) {
      runif(1, min = (year - 2008) / 8, max = (year - 1998) / 8)
    }, data_raw$year) + rgamma(observation_num, time_params[1], time_params[2])[data_raw$id]
  }
  
  # individual covariates
  if (id_type == "Exponential") {
    data_raw$z1 = exp(rnorm(observation_num, mean = id_params[1], sd = id_params[2]))[data_raw$id]
  } else if (id_type == "Poisson") {
    data_raw$z1 = rpois(observation_num, id_params[1])[data_raw$id]
  } else if (id_type == "Gamma") {
    data_raw$z1 = rgamma(observation_num, id_params[1], id_params[2])[data_raw$id]
  }
  
  # outcome
  data_raw$y = beta_0 + beta_1 * data_raw$x1 + b_0i[data_raw$id] + b_1i[data_raw$id] * data_raw$x1 + beta_2 * data_raw$z1
  rsd = rnorm(nrow(data_raw), 0, 1)
  data_raw$y = data_raw$y + rsd
  
  # missing values
  data = introduce_missingness(data_raw, "MAR", "x1", 0.3)
  data = introduce_missingness(data, "MAR", "z1", 0.9)
  data = introduce_missingness(data, "MAR", "y", 0.8)
  
  return(list(data = data, raw = data_raw))
}
```



```{r}
# start time
start_time = Sys.time()

# set up multi-cores
run_on_cluster(
  # use SimEngine
  first = {
    sim = new_sim()
    
    sim %<>% set_levels(
      observation_num = c(50, 100, 200),
      start_years = 2000,
      time_list = list(
        "Norm" = list(time_type = "Normal", time_params = c(4, 5, 2, 1), time_beta = 0.7),
        "Pois" = list(time_type = "Poisson", time_params = 8, time_beta = 2),
        "Uni" = list(time_type = "Uniform", time_params = c(1, 3), time_beta = 11)
      ),
      id_list = list(
        "Exp" = list(id_type = "Exponential", id_params = c(log(sqrt(3.2)), log(sqrt(5/4))), id_beta = 3),
        "Pois" = list(id_type = "Poisson", id_params = 2, id_beta = 1.5),
        "Gam" = list(id_type = "Gamma", id_params = c(3, 2), id_beta = 12)
      )
    )
    
    sim %<>% set_config(num_sim = 1000, n_cores = 4, seed = 1018,
                        packages = c("dplyr", "parallel", "MASS", "Matrix", "mice", "miceadds")
    )
    
    sim %<>% set_script(function() {
      data = create_data(L$observation_num, L$start_year, L$time_list$time_type, L$time_list$time_params, L$time_list$time_beta, L$id_list$id_type, L$id_list$id_params, L$id_list$id_beta)$data
  data_raw = create_data(L$observation_num, L$start_year, L$time_list$time_type, L$time_list$time_params, L$time_list$time_beta, L$id_list$id_type, L$id_list$id_params, L$id_list$id_beta)$raw
      
      # imputation dataset
      data_use = data %>%
        dplyr::select(id, year, x1, z1, y)
      data_use$id = as.integer(data_use$id)
      data_use = data_use %>%
        mutate_all(~ifelse(. == "NaN", NA, .))
      
      # set imputation parameters
      ini = mice(data_use, maxit = 0)
      
      pred = ini$pred
      pred[1:nrow(pred), 1:ncol(pred)] = 0
      pred[, "id"] = (-2)
      pred[, "year"] = (-1)
      pred[, c("x1")] = 3
      pred[, "y"] = 4
      pred["z1", ] = c(0, 0, 1, 1, 0)
      diag(pred) = 0
      
      meth2l = ini$meth
      meth = ini$meth
      meth2l[c("x1", "y")] = c("2l.pmm", "2l.pmm")
      meth[c("x1", "y")] = c("pmm", "pmm")
      
      # imputation process
      m = 5
      imp.use2l = mice(data_use, pred = pred, meth = meth2l, m = m, maxit = 5, seed = 1018, printFlag = F)
      imp.use = mice(data_use, pred = pred, meth = meth, m = m, maxit = 5, seed = 1018, printFlag = F)
      
      mean_x1_2lpmm = c()
      mean_x1_pmm = c()
      for (i in (1: m)) {
        mean_x1_2lpmm[i] = mean(complete(imp.use2l, i)$x1)
        mean_x1_pmm[i] = mean(complete(imp.use, i)$x1)
      }
      
      x1_2lpmm = mean(mean_x1_2lpmm)
      x1_pmm = mean(mean_x1_pmm)
      x1_true = mean(data_raw$x1)
      
      return(list(
        "x1_true" = x1_true,
        "x1_2lpmm" = x1_2lpmm,
        "x1_pmm" = x1_pmm,
        "x1_2l_pctg" = (x1_2lpmm - x1_true) / x1_true * 100,
        "x1_1l_pctg" = (x1_pmm - x1_true) / x1_true * 100,
        ".complex" = list(
          "data_raw" = data_raw,
          "data" = data
        )
      ))
    })
  },
  
  main = {
    sim %<>% run()
    print(sim$errors)
  },
  
  last = {
    # bias
    bias_x1 = sim %>% SimEngine::summarize(
      list(stat = "bias", estimate = "x1_2lpmm", truth = "x1_true", name = "bias_x1_2l"),
      list(stat = "bias", estimate = "x1_pmm", truth = "x1_true", name = "bias_x1_1l"),
      list(stat = "mse", estimate = "x1_2lpmm", truth = "x1_true", name = "mse_x1_2l"),
      list(stat = "mse", estimate = "x1_pmm", truth = "x1_true", name = "mse_x1_1l")
      # list(stat = "coverage", lower = "2l_low", upper = "2l_up", truth = "x1_true", name = "cov_x1_2l"),
      # list(stat = "coverage", lower = "1l_low", upper = "1l_up", truth = "x1_true", name = "cov_x1_1l")
    )
    # bias percentage
    bias_x1_pct = sim %>% SimEngine::summarize(
      list(stat = "mean", x = "x1_2l_pctg", name = "bias_x1_2lpmm"),
      list(stat = "mean", x = "x1_1l_pctg", name = "bias_x1_pmm")
    )
  },
  
  cluster_config = list(js = "slurm")
)



# end time
end_time = Sys.time()
execution_time = end_time - start_time
print(execution_time)
```





try
```{r}
observation_num = 1000
all_years = all_years = seq(1990, 2020, by = 2)
time_cvr = list(
  "Norm" = list(distr_type = "Normal", distr_params = c(4, 5, 2, 1), beta = 0.7),
  "Pois" = list(distr_type = "Poisson", distr_params = 8, beta = 2),
  "Uni" = list(distr_type = "Uniform", distr_params = c(1, 3), beta = 11)
)
id_cvr = list(
  "Exp" = list(distr_type = "Exponential", distr_params = c(log(sqrt(3.2)), log(sqrt(5/4))), beta = 3),
  "Pois" = list(distr_type = "Poisson", distr_params = 2, beta = 1.5),
  "Gam" = list(distr_type = "Gamma", distr_params = c(3, 2), beta = 12)
)




data = create_data(observation_num, all_years, "Uniform", c(1, 3), 11, "Gamma", c(3, 2), 12)$data



# imputation dataset
data_use = data %>%
  dplyr::select(id, year, x1, z1, y)
data_use$id = as.integer(data_use$id)
data_use = data_use %>%
  mutate_all(~ifelse(. == "NaN", NA, .))

# set imputation parameters
ini = mice(data_use, maxit = 0)

pred = ini$pred
pred[1:nrow(pred), 1:ncol(pred)] = 0
pred[, "id"] = (-2)
pred[, "year"] = (-1)
pred[, c("x1")] = 3
pred[, "y"] = 4
pred["z1", ] = c(0, 0, 1, 1, 0)
diag(pred) = 0

meth2l = ini$meth
meth = ini$meth
meth2l[c("x1", "y")] = c("2l.pmm", "2l.pmm")
meth[c("x1", "y")] = c("pmm", "pmm")

m = 5
imp.use2l = mice(data_use, pred = pred, meth = meth2l, m = m, maxit = 5, seed = 1018, printFlag = F)

mean_x1_2lpmm = c()
for (i in (1: m)) {
  mean_x1_2lpmm[i] = mean(complete(imp.use2l, i)$x1)
}


```






